//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIteDisplayAutomationResults
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST_STATUS_TB
    {
        public string Test_ID { get; set; }
        public string ACTION { get; set; }
        public string STATUS { get; set; }
        public string ERROR_DETAILS { get; set; }
        public string COMPONENT_ID { get; set; }
        public Nullable<System.DateTime> Creation_Time { get; set; }
        public string HOST { get; set; }
    }
}
